<a href="https://colab.research.google.com/github/SeptiLutfiana/MESIN-LEARNING/blob/main/Pertemuan9_Praktikum4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Septi Lutfiana
- 2141720038
- 3H D-4 TI

# Pra Pengolahan Data

## Langkah 1 - Import Library

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Langkah 2 - Load Data

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/ML/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


# Langkah 3 - Encoding Data Kategorikal

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

# Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Langkah 5 - Split Data

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Langkah 6 - Scaling Fitur

# Membuat Model ANN

### Langkah 1 - Inisiasi Model ANN

In [10]:
ann = tf.keras.models.Sequential()

### Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Langkah 3 - Membuat Hidden Layer Kedua

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Langkah 4 - Membuat Output Layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training Model

### Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Langkah 2 - Fitting Model

In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 4613.9077 - accuracy: 0.5052
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 49.7241 - accuracy: 0.6329
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 26.8562 - accuracy: 0.6506
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 22.4649 - accuracy: 0.6550
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 18.0822 - accuracy: 0.6661
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 23.9864 - accuracy: 0.6715
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 27.0576 - accuracy: 0.6769
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 23.5976 - accuracy: 0.6815
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 27.2020 - accuracy: 0.6793
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 19.4

# Membuat Prediksi

### Modelkan Data Baru dan Buat Prediksi

In [29]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

NameError: ignored

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

ValueError: ignored